#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: MyCdA.App Blog

# Short bio or description (displayed in the header)
description: User documentation, FAQ, Support and aero talk

long_description: MyCdA.App blog. MyCdA.app lets you use data collected using a power meter, speed sensor and a cycling computer and estimate your drag coefficient (CdA) and /or rolling resistance (crr). Compare data across different runs in order to determine if an equipment or position change is beneficial or not. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.gravatar.com/avatar/88f2dcb55eee58d2adaaab0cac7dc495

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  facebook:
  github: mariuspopovici/mycda.app
  instagram:
  linkedin:
  rss: # just type anything here for a working RSS icon
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: mycda

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.mycda.app

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ''

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:year/:month/:title.html

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Pagination Settings - These are for jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - Page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate-v2 # Enable post paging - This plugin doesn't work on Github Pages
  - jekyll-youtube
  - jekyll-picture-tag

picture:
  source: 'assets/images/_fullsize'
  output: 'assets/images/generated'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
